import "@cloudscape-design/global-styles/index.css";
import { Inter } from "next/font/google";
import { IInitialState } from "@/store";
import { StoreProvider } from "@/providers/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

const initialData: IInitialState = {
  counterStore: {},
  githubStore: {},
};

export default async function RootLayout({ children }: Props) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <StoreProvider initialState={initialData}>{children}</StoreProvider>
      </body>
    </html>
  );
}
